### ISSUE TITLE
Idea: Tidy evaluation and shiny

### ISSUE THREAD

**Issue by rpodcast** [jcheng5/shiny-book#1]
I hope you don't mind having user feedback at this early stage 😄 

I think there should be a section devoted to how a developer can take advantage of [tidy evaluation](https://tidyeval.tidyverse.org/). Ever since your keynote at R/Pharma 2018 with the demo of the [possibilities](https://github.com/jcheng5/rpharma-demo), it was a real 👀 opener and I could see that being relevant to not just pharma use cases.

**Comment by MarkusLang1987** [comment]
# Would love that too.

**Comment by hadley** [comment]
Noted in the outline.
