### ISSUE TITLE
Add a reactive graph diagram with reactive expressions

### ISSUE THREAD

**Issue by cpsievert** [jcheng5/shiny-book#3]
There is a diagram here with just reactive values and observers.

https://github.com/jcheng5/shiny-book/blob/6116549ee9181d761d210a624590d5dde38fcaf4/07-demystifying-reactivity.Rmd#L193

I think it would be nice to have another diagram, maybe below this paragraph, with all three (reactive values, expressions, and observers) 

https://github.com/jcheng5/shiny-book/blob/6116549ee9181d761d210a624590d5dde38fcaf4/07-demystifying-reactivity.Rmd#L196

**Comment by hadley** [comment]
Now included in https://mastering-shiny.org/basic-reactivity.html. The example is a in state of flux, but the goal is to describe all the basic components here.
