### ISSUE TITLE
What is a side-effect?

### ISSUE THREAD

**Issue by cpsievert** [jcheng5/shiny-book#4]
https://github.com/jcheng5/shiny-book/blob/6116549ee9181d761d210a624590d5dde38fcaf4/07-demystifying-reactivity.Rmd#L220

> Though outputs allow (and may even require) side effects, this doesn’t mean you should include just any side effects in your output code.

In the previous paragraph, you mention that `renderPrint()` expects calls to `print()` , and `renderPlot()` (may) expect you to draw a plot, but you don't explicitly mention these are side-effects. I think it would be good to be a little more explicit about that (i.e., don't leave your readers wondering: what is a side-effect? when and why do outputs require them?)

It might also be worthwhile demonstrating or explaining *why* you should avoid side-effects in your output code (and maybe even in general), even if you just point to another section or appendix

**Comment by hadley** [comment]
Restored side-effect fragment into building blocks of reactivity. Will appear shortly on https://mastering-shiny.org/reactivity-mental-model.html
