### ISSUE TITLE
Consider setting message=FALSE, warning=FALSE, etc globally 

### ISSUE THREAD

**Issue by cpsievert** [jcheng5/shiny-book#5]
Especially relevant for 

https://github.com/jcheng5/shiny-book/blob/6116549ee9181d761d210a624590d5dde38fcaf4/07-demystifying-reactivity.Rmd#L247-L253

**Comment by hadley** [comment]
I think it's better to do this on a case-by-case basis — otherwise it's too easy to suppress something important.
